**Numpy**

In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
# print(type(a))
print(a)
# x=[1,2,3,4,5]
# print(type(x))
# x=np.array(x)
# print(type(x))
zeros_array = np.zeros(5)
ones_array = np.ones((2,3)) 
print(zeros_array)
print(ones_array)
a=np.arange(9)
print(a)


[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8]


In [23]:
a=np.arange(9)
print(a)
a=a.reshape(-1,3)
print(a.shape)
print(a)

[0 1 2 3 4 5 6 7 8]
(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
l1=np.array([1,2,3,4,5])
l2=np.array([4,5,6,7,8])
s=l1+l2
print(s)
d=l2-l1
print(d)
m=l1*l2
print(m)
if not np.any(l2==0):
    di=l1/l2
else:
    raise ValueError("Error")
print(di)

[ 5  7  9 11 13]
[3 3 3 3 3]
[ 4 10 18 28 40]
[0.25       0.4        0.5        0.57142857 0.625     ]


In [18]:

l1 = np.array([[1, 2, 3, 4, 5]]) 
l2 = np.array([[4], [5], [6], [7], [8]]) 
m = np.matmul(l1, l2)
print("Matrix Multiplication:", m)
l3 = np.transpose(l1)
l4 = l1.reshape(-1, 1)
print(l3.shape)
print( l4.shape)
print(l3)
print(l4)

Matrix Multiplication: [[100]]
(5, 1)
(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [20]:
l1=np.array([1, 2, 3, 4, 5])
print(l1[4:5])
print(l1[::2])
print(l1[::4])


[5]
[1 3 5]
[1 5]


In [25]:
a=np.array([1,5,6,8,10,7])
print(np.amax(a))
print(np.amin(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.argmax(a))

10
1
6.166666666666667
6.5
2.7938424357067015
4
