In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(m)
m = np.array([1, 2, 3, 4], ndmin=5)
print(m)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[[[1 2 3 4]]]]]


In [3]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
n = np.array([[9,8,7], [6,5,4], [3,2,1]])
x=np.matmul(m,n)
print(x)
s=m+n
print(s)
d=n-m
print(d)
if not np.any(n==0):
    di=m/n
else:
    raise ValueError("Error")
print(di)

g=m.reshape(1,9)
print(g)
h=n.reshape(9,1)
print(h)
j=np.transpose(m)
print(j)
k=np.transpose(n)
print(k)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[ 8  6  4]
 [ 2  0 -2]
 [-4 -6 -8]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
[[1 2 3 4 5 6 7 8 9]]
[[9]
 [8]
 [7]
 [6]
 [5]
 [4]
 [3]
 [2]
 [1]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[9 6 3]
 [8 5 2]
 [7 4 1]]


In [26]:
#Q4
'''
Read the dataset given in data.txt and perform following experiments
a. Find the serial number of the students who have got 5 marks
b. Take the roll number of the students and print the roll number in the following
interval using numPy arrays.
i. 2
ii. 4
iii. 6
iv. 10
c. Print the serial number and roll number of the student who have got maximum
number
'''
with open('data.txt', 'r') as file:
    lines = file.readlines()[1:]


roll_numbers = []
scores = []


for line in lines:
    data = line.split('\t')  
    roll_numbers.append(int(data[0]))
    scores.append(int(data[1]))


roll_numbers = np.array(roll_numbers)
scores = np.array(scores)


students_with_5_marks = roll_numbers[scores == 5]
print(f'Students with 5 marks: {students_with_5_marks}')


intervals = [2, 4, 6, 10]
for interval in intervals:
    print(f'Roll numbers in interval of {interval}: {roll_numbers[::interval]}')


max_score_index = np.argmax(scores)
print(f'Student with maximum score: Roll Number - {roll_numbers[max_score_index]}')
#Q5
mean_score = np.mean(scores)
print(f"Mean score: {mean_score}")


median_score = np.median(scores)
print(f"Median score: {median_score}")


mode_score = np.std(scores)
print(f"Mode score: {mode_score}")

Students with 5 marks: [ 2005058  2005150  2005179  2005278  2005324  2005407  2005473  2005574
  2005585  2005601  2005704  2005721  2005929 20051001 20051182 20051254
 20051329 20051433 20051805 20051915 21053047]
Roll numbers in interval of 2: [ 2005011  2005076  2005150  2005168  2005179  2005270  2005288  2005312
  2005326  2005343  2005439  2005473  2005548  2005574  2005585  2005597
  2005601  2005608  2005631  2005704  2005721  2005904  2005929  2005979
 20051023 20051049 20051122 20051164 20051174 20051254 20051351 20051362
 20051397 20051433 20051473 20051552 20051614 20051805 20051866 20051872
 20051903 20051962 21053002 21053022 21053047 21053067]
Roll numbers in interval of 4: [ 2005011  2005150  2005179  2005288  2005326  2005439  2005548  2005585
  2005601  2005631  2005721  2005929 20051023 20051122 20051174 20051351
 20051397 20051473 20051614 20051866 20051903 21053002 21053047]
Roll numbers in interval of 6: [ 2005011  2005168  2005288  2005343  2005548  2005597  200

In [25]:
mean_score = np.mean(scores)
print(f"Mean score: {mean_score}")


median_score = np.median(scores)
print(f"Median score: {median_score}")


mode_score = np.std(scores)
print(f"Mode score: {mode_score}")

Mean score: 4.032967032967033
Median score: 4.0
Mode score: 0.8701465008716112
